6element:
   build: .
   command: npm run init-prod
   links:
      - db
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_HOST=6element.ants.builders 
      - VIRTUAL_PORT=4000
      - POSTGRES_PASSWORD=elements
   volumes:
      - core:/6element/core

db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements
   restart: always

