6element:
  build: ./app
  command: npm run dev
  links:
   - db:postgres
  ports:
   - 4000:4000
   - 35729:35729
  environment:
   - VIRTUAL_HOST=6element.ants.builders 
   - VIRTUAL_PORT=4000
   - DEBUG=true
  volumes:
   - app:/6element/app
db:
  image: postgres:9.4
  environment:
   - POSTGRES_PASSWORD=password
  ports:
   - 5432:5432
tests:
  build: ./tests
  links:
   - 6element
  command: node ./src/index.js
  volumes:
   - tests:/tests/src