6element:
   build: .
   command: npm run start-app-prod
   links:
      - db
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_HOST=6element.ants.builders 
      - VIRTUAL_PORT=4000
      - POSTGRES_PASSWORD=elements
   volumes:
      - app:/6element/app
   restart: always
admin:
   build: .
   command: npm run start-admin-prod
   links:
      - db
   ports:
      - "4001:4001"
   environment:
      - VIRTUAL_HOST=admin.6element.ants.builders 
      - VIRTUAL_PORT=4001
      - POSTGRES_PASSWORD=elements
   volumes:
      - app:/6element/app
   restart: always
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements
   restart: always
