// autogenerated by sql-generate v1.0.0 on Fri Jul 10 2015 13:42:44 GMT+0000 (UTC)

var sql = require('sql');


/**
 * SQL definition for public.affluence_sensor_measurements
 */
exports.affluence_sensor_measurements = sql.define({
	name: 'affluence_sensor_measurements',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'sensor_id' },
		{ name: 'signal_strengths' },
		{ name: 'measurement_date' }
	]
});


/**
 * SQL definition for public.lifecycle
 */
exports.lifecycle = sql.define({
	name: 'lifecycle',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' }
	]
});


/**
 * SQL definition for public.places
 */
exports.places = sql.define({
	name: 'places',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'type' },
		{ name: 'lat' },
		{ name: 'lon' }
	]
});


/**
 * SQL definition for public.sensors
 */
exports.sensors = sql.define({
	name: 'sensors',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'installed_at' },
		{ name: 'phone_number' },
		{ name: 'quipu_status' },
		{ name: 'sense_status' },
		{ name: 'latest_input' },
		{ name: 'latest_output' }
	]
});


